//Initialise functions
{
  function loadWTOArmyORBAT () {
    //Declare local instance variables
    var wto_army_orbat = [
      ['23rd Tank Regiment', 'Zeithain', 'armour'],
      ['95th Tank Regiment', 'Zeithain', 'armour'],
      ['70th Guards Tank Regiment', 'Zeithain', 'armour'],
      ['302nd Motorised Rifle Regiment', 'Riesa', 'infantry'],
      ['96th Artillery Regiment', 'Borna', 'artillery'],
      ['216th Anti-Aircraft Missile Regiment', 'Zeithain', 'air'],
      ['13th Independent Reconaissance Battalion', 'Zeithain', 'infantry'],
      ['109th Independent Engineer-Sapper Battalion', 'Oschatz', 'infantry'],
      ['696th Independent Communications Battalion', 'Riesa', 'infantry'],
      ['68th Independent Equipment Maintenance and Recovery Battalion', 'Zeithain', 'infantry'],
      ['112th Independent Chemical Defence Battalion', 'Riesa', 'infantry'],
      ['1071st Independent Material Supply Battalion', 'Oschatz', 'infantry'],
      ['7th Guards Tank Regiment', 'Meissen', 'armour'],
      ['40th Guards Tank Regiment', 'Königsbrück', 'armour'],
      ['44th Guards Tank Regiment', 'Königsbrück', 'armour'],
      ['249th Guards Motorised Rifle Regiment', 'Dresden-Klotzsche', 'infantry'],
      ['841st Guards Artillery Regiment', 'Karl-Marx-Stadt', 'artillery'],
      ['1018th Anti-Aircraft Missile Regiment', 'Meissen', 'air'],
      ['9th Independent Guards Reconaissance Battalion', 'Dresden-Klotzsche', 'infantry'],
      ['134th Independent Guards Engineer-Sapper Battalion', 'Königsbrück', 'infantry'],
      ['153rd Independent Guards Communications Battalion', 'Dresden-Klotzsche', 'infantry'],
      ['61st Independent Equipment Maintenance and Recovery Battalion', 'Dresden-Klotzsche', 'infantry'],
      ['128th Independent Chemical Defence Battalion', 'Königsbrück', 'infantry'],
      ['1073rd Independent Material Supply Battalion', 'Königsbrück', 'infantry'],
      ['29th Guards Motorised Rifle Regiment', 'Plauen', 'infantry'],
      ['67th Guards Motorised Rifle Regiment', 'Grimma', 'infantry'],
      ['242nd Guards Motorised Rifle Regiment', 'Wurzen', 'infantry'],
      ['1st Guards Tank Regiment', 'Glauchau', 'armour'],
      ['944th Guards Artillery Regiment', 'Leisnig', 'artillery'],
      ['358th Guards Anti-Aircraft Missile Regiment', 'Leisnig', 'air'],
      ['20th Independent Tank Battalion', 'Plauen', 'armour'],
      ['320th Independent Missile Battalion', 'Leisnig', 'artillery'],
      ['487th Independent Anti-Tank Artillery Battalion', 'Leisnig', 'artillery'],
      ['68th Independent Guards Reconaissance Battalion', 'Plauen', 'infantry'],
      ['133rd Independent Guards Engineer-Sapper Battalion', 'Leipzig', 'infantry'],
      ['454th Independent Guards Communications Battalion', 'Grimma', 'infantry'],
      ['39th Independent Equipment Maintenance and Recovery Battalion', 'Leipzig', 'infantry'],
      ['347th Independent Medical Battalion', 'Grimma', 'infantry'],
      ['1124th Independent Material Supply Battalion', 'Grimma', 'infantry'],
      ['33rd Motorised Rifle Regiment', 'Stendal', 'infantry'],
      ['41st Motorised Rifle Regiment', 'Gardelegen', 'infantry'],
      ['245th Guards Motorised Rifle Regiment', 'Magdeburg', 'infantry'],
      ['16th Guards Tank Regiment', 'Stendal', 'armour'],
      ['693rd Artillery Regiment', 'Stendal', 'artillery'],
      ['75th Guards Anti-Aircraft Missile Regiment', 'Stendal', 'air'],
      ['32nd Independent Tank Battalion', 'Gardelegen', 'armour'],
      ['301st Independent Missile Battalion', 'Gardelegen', 'artillery'],
      ['498th Independent Anti-Tank Artillery Battalion', 'Gardelegen', 'artillery'],
      ['6th Independent Reconaissance Battalion', 'Gardelegen', 'infantry'],
      ['338th Independent Engineer-Sapper Battalion', 'Stendal', 'infantry'],
      ['912th Independent Communications Battalion', 'Stendal', 'infantry'],
      ['517th Independent Chemical Defence Battalion', 'Stendal', 'infantry'],
      ['46th Independent Equipment Maintenance and Recovery Battalion', 'Gardelegen', 'infantry'],
      ['1131st Independent Material Supply Battalion', 'Stendal', 'infantry'],
      ['47th Guards Tank Regiment', 'Neustrelitz', 'armour'],
      ['65th Guards Tank Regiment', 'Neustrelitz', 'armour'],
      ['67th Guards Tank Regiment', 'Rathenov', 'armour'],
      ['60th Motorised Rifle Regiment', 'Ravensbrück', 'infantry'],
      ['724th Guards Artillery Regiment', 'Neustrelitz', 'artillery'],
      ['66th Guards Anti-Aircraft Missile Regiment', 'Neustrelitz', 'air'],
      ['17th Independent Guards Reconnaissance Battalion', 'Neustrelitz', 'infantry'],
      ['668th Independent Missile Battalion', 'Neustrelitz', 'artillery'],
      ['135th Independent Guards Engineer-Sapper Battalion', 'Neustrelitz', 'infantry'],
      ['135th Independent Guards Engineer-Sapper Battalion', 'Neustrelitz', 'infantry'], // Duplicate entry
      ['18th Independent Guards Communications Battalion', 'Neustrelitz', 'infantry'],
      ['59th Independent Equipment Maintenance and Recovery Battalion', 'Neustrelitz', 'infantry'],
      ['541st Independent Chemical Defence Battalion', 'Neustrelitz', 'infantry'],
      ['1075th Independent Material Supply Battalion', 'Neustrelitz', 'infantry'],
      ['162nd Tank Regiment', 'Vogelsang', 'armour'],
      ['175th Tank Regiment', 'Prenzlau', 'armour'],
      ['335th Guards Tank Regiment', 'Prenzlau', 'armour'],
      ['803rd Guards Motorised Rifle Regiment', 'Drögen', 'infantry'],
      ['843rd Guards Artillery Regiment', 'Schönwalde', 'artillery'],
      ['447th Anti-Aircraft Missile Regiment', 'Vogelsang', 'air'],
      ['665th Independent Missile Battalion', 'Vogelsang', 'artillery'],
      ['53rd Independent Reconaissance Battalion', 'Prenzlau', 'infantry'],
      ['196th Independent Engineer-Sapper Battalion', 'Vogelsang', 'infantry'],
      ['459th Independent Communications Battalion', 'Vogelsang', 'infantry'],
      ['159th Independent Chemical Defence Battalion', 'Vogelsang', 'infantry'],
      ['14th Independent Equipment Maintenance and Recovery Battalion', 'Vogelsang', 'infantry'],
      ['1076th Independent Material Supply Battalion', 'Britz', 'infantry'],
      ['239th Motorised Rifle Regiment', 'Perleberg', 'infantry'],
      ['240th Motorised Rifle Regiment', 'Ludwigslust', 'infantry'],
      ['283rd Guards Motorised Rifle Regiment', 'Hagenau', 'infantry'],
      ['33rd Tank Regiment', 'Parchim', 'armour'],
      ['1054th Artillery Regiment', 'Rathenow', 'artillery'],
      ['1079th Anti-Aircraft Missile Regiment', 'Perleberg', 'air'],
      ['18th Independent Tank Battalion', 'Parchim', 'armour'],
      ['298th Independent Missile Battalion', 'Ludwigslust', 'artillery'],
      ['480th Independent Anti-Tank Artillery Battalion', 'Ludwigslust', 'artillery'],
      ['34th Independent Reconaissance Battalion', 'Perleberg', 'infantry'],
      ['348th Independent Engineer-Sapper Battalion', 'Luddwigslust', 'infantry'], // Typo: Luddwigslust -> Ludwigslust
      ['921st Independent Communications Battalion', 'Perleberg', 'infantry'],
      ['518th Independent Chemical Defence Battalion', 'Parchim', 'infantry'],
      ['34th Independent Equipment Maintenance and Recovery Battalion', 'Ludwigslust', 'infantry'],
      ['1125th Independent Material Supply Battalion', 'Perleberg', 'infantry'],
      ['204th Guards Motorised Rifle Regiment', 'Schwerin', 'infantry'],
      ['286th Guards Motorised Rifle Regiment', 'Schwerin', 'infantry'],
      ['288th Guards Motorised Rifle Regiment', 'Wismar', 'infantry'],
      ['74th Guards Tank Regiment', 'Schwerin', 'armour'],
      ['199th Guards Artillery Regiment', 'Wismar', 'artillery'],
      ['896th Anti-Aircraft Missile Regiment', 'Wismar', 'air'],
      ['28th Independent Tank Battalion', 'Hagenow', 'armour'],
      ['1562nd Independent Missile Battalion', 'Hagenow', 'artillery'],
      ['496th Independent Anti-Tank Artillery Battalion', 'Schwerin', 'artillery'],
      ['12th Independent Guards Reconnaissance Battalion', 'Schwerin', 'infantry'],
      ['107th Independent Guards Engineer-Sapper Battalion', 'Schwerin', 'infantry'],
      ['159th Independent Guards Communications Battalion', 'Schwerin', 'infantry'],
      ['365th Independent Chemical Defence Battalion', 'Schwerin', 'infantry'],
      ['52nd Independent Equipment Maintenance and Recovery Battalion', 'Schwerin', 'infantry'],
      ['90th Independent Medical Battalion', 'Schwerin', 'infantry'],
      ['1130th Independent Material Supply Battalion', 'Schwerin', 'infantry'],
      ['48th Guards Tank Regiment', 'Neuruppin', 'armour'],
      ['332nd Guards Tank Regiment', 'Neuruppin', 'armour'],
      ['353rd Guards Tank Regiment', 'Neuruppin', 'armour'],
      ['200th Guards Motorised Rifle Regiment', 'Mahlwinkel', 'infantry'],
      ['117th Artillery Regiment', 'Mahlwinkel', 'artillery'],
      ['933rd Anti-Aircraft Missile Regiment', 'Burg', 'air'],
      ['18th Independent Guards Reconnaissance Battalion', 'Mahlwinkel', 'infantry'],
      ['639th Independent Missile Battalion', 'Neuruppin', 'artillery'],
      ['136th Independent Guards Engineer-Sapper Battalion', 'Neuruppin', 'infantry'],
      ['490th Independent Guards Communications Battalion', 'Neuruppin', 'infantry'],
      ['64th Independent Equipment Maintenance and Recovery Battalion', 'Neuruppin', 'infantry'],
      ['129th Independent Chemical Defence Battalion', 'Schönwalde', 'infantry'],
      ['208th Independent Medical Battalion', 'Neuruppin', 'infantry'],
      ['1074th Independent Material Supply Battalion', 'Wulkov', 'infantry'],
      ['55th Guards Tank Regiment', 'Dessau-Kochstedt', 'armour'],
      ['56th Guards Tank Regiment', 'Zerbst', 'armour'],
      ['79th Guards Tank Regiment', 'Rosslau', 'armour'],
      ['40th Motorised Rifle Regiment', 'Bernburg', 'infantry'],
      ['670th Guards Artillery Regiment', 'Dessau-Kochstedt', 'artillery'],
      ['287th Guards Anti-Aircraft Missile Regiment', 'Rosslau', 'air'],
      ['4th Independent Guards Reconnaissance Battalion', 'Dessau-Kochstedt', 'infantry'],
      ['650th Independent Missile Battalion', 'Rosslau', 'artillery'],
      ['121st Independent Guards Engineer-Sapper Battalion', 'Rosslau', 'infantry'],
      ['146th Independent Guards Communications Battalion', 'Rosslau', 'infantry'],
      ['58th Independent Equipment Maintenance and Recovery Battalion', 'Rosslau', 'infantry'],
      ['165th Independent Chemical Defence Battalion', 'Rosslau', 'infantry'],
      ['186th Independent Medical Battalion', 'Dessau', 'infantry'],
      ['183rd Independent Material Supply Battalion', 'Rosslau', 'infantry'],
      ['61st Guards Tank Regiment', 'Krampnitz', 'armour'],
      ['62nd Guards Tank Regiment', 'Potsdam', 'armour'],
      ['63rd Guards Tank Regiment', 'Potsdam', 'armour'],
      ['248th Guards Motorised Rifle Regiment', 'Krampnitz', 'infantry'],
      ['744th Guards Artillery Regiment', 'Potsdam', 'artillery'],
      ['359th Guards Anti-Aircraft Missile Regiment', 'Potsdam', 'air'],
      ['7th Independent Guards Reconnaissance Battalion', 'Krampnitz', 'infantry'],
      ['697th Independent Missile Battalion', 'Krampnitz', 'artillery'],
      ['131st Independent Guards Engineer-Sapper Battalion', 'Krampnitz', 'infantry'],
      ['152nd Independent Guards Communications Battalion', 'Krampnitz', 'infantry'],
      ['60th Independent Equipment Maintenance and Recovery Battalion', 'Krampnitz', 'infantry'],
      ['127th Independent Chemical Defence Battalion', 'Krampnitz', 'infantry'],
      ['188th Independent Medical Battalion', 'Krampnitz', 'infantry'],
      ['1072nd Independent Material Supply Battalion', 'Krampnitz', 'infantry'],
      ['26th Tank Regiment', 'Hillersleben', 'armour'],
      ['153rd Tank Regiment', 'Hillersleben', 'armour'],
      ['197th Guards Tank Regiment', 'Halberstadt', 'armour'],
      ['245th Guards Motorised Rifle Regiment', 'Magdeburg', 'infantry'],
      ['99th Guards Artillery Regiment', 'Magdeburg', 'artillery'],
      ['1069th Anti-Aircraft Missile Regiment', 'Hillersleben', 'air'],
      ['664th Independent Missile Battalion', 'Hillersleben', 'artillery'],
      ['112th Independent Reconnaissance Battalion', 'Hillersleben', 'infantry'],
      ['52nd Independent Guards Engineer-Sapper Battalion', 'Hillersleben', 'infantry'],
      ['73rd Independent Guards Communications Battalion', 'Hillersleben', 'infantry'],
      ['000 Independent Chemical Defence Battalion', 'Magdeburg', 'infantry'], // Unusual numbering
      ['65th Independent Equipment Maintenance and Recovery Battalion', 'Hillersleben', 'infantry'],
      ['63rd Independent Medical Battalion', 'Hillersleben', 'infantry'],
      ['1077th Independent Material Supply Battalion', 'Hillersleben', 'infantry'],
      ['17th Guards Tank Regiment', 'Saalfeld', 'armour'],
      ['45th Guards Tank Regiment', 'Weimar', 'armour'],
      ['211th Tank Regiment', 'Jena', 'armour'],
      ['247th Guards Motorised Rifle Regiment', 'Weimar', 'infantry'],
      ['172nd Guards Artillery Regiment', 'Rudolstadt', 'artillery'],
      ['1075th Anti-Aircraft Missile Regiment', 'Weimar', 'air'],
      ['345th Independent Missile Battalion', 'Rudolstadt', 'artillery'],
      ['10th Independent Guards Reconnaissance Battalion', 'Rudolstadt', 'infantry'],
      ['88th Independent Guards Engineer-Sapper Battalion', 'Jena', 'infantry'],
      ['110th Independent Guards Communications Battalion', 'Jena', 'infantry'],
      ['000 Independent Chemical Defence Battalion', 'Jena', 'infantry'], // Unusual numbering
      ['66th Independent Equipment Maintenance and Recovery Battalion', 'Jena', 'infantry'],
      ['83rd Independent Medical Battalion', 'Jena', 'infantry'],
      ['1079th Independent Material Supply Battalion', 'Jena', 'infantry'],
      ['345th Independent Helicopter Detachment', 'Weimar-Nohra', 'air'],
      ['117th Guards Motorised Rifle Regiment', 'Meiningen', 'infantry'],
      ['120th Guards Motorised Rifle Regiment', 'Ohrdruf', 'infantry'],
      ['172nd Guards Motorised Rifle Regiment', 'Gotha', 'infantry'],
      ['15th Guards Tank Regiment', 'Ohrdruf', 'armour'],
      ['87th Guards Artillery Regiment', 'Gotha', 'artillery'],
      ['915th Anti-Aircraft Missile Regiment', 'Ohrdruf', 'air'],
      ['23rd Independent Tank Battalion', 'Meiningen', 'armour'],
      ['1563rd Independent Missile Battalion', 'Gotha', 'artillery'],
      ['489th Independent Anti-Tank Artillery Battalion', 'Meiningen', 'artillery'],
      ['11th Independent Guards Reconnaissance Battalion', 'Meiningen', 'infantry'],
      ['272nd Independent Guards Engineer-Sapper Battalion', 'Ohrdruf', 'infantry'],
      ['154th Independent Guards Communications Battalion', 'Ohrdruf', 'infantry'],
      ['514th Independent Chemical Defence Battalion', 'Gotha', 'infantry'],
      ['49th Independent Equipment Maintenance and Recovery Battalion', 'Ohrdruf', 'infantry'],
      ['33rd Independent Medical Battalion', 'Ohrdruf', 'infantry'],
      ['1128th Independent Material Supply Battalion', 'Ohrdruf', 'infantry'],
      ['241st Independent Helicopter Detachment', 'Weimar-Nohra', 'air'],
      ['170th Guards Motorised Rifle Regiment', 'Naumburg', 'infantry'],
      ['174th Guards Motorised Rifle Regiment', 'Weissenfels', 'infantry'],
      ['241st Guards Motorised Rifle Regiment', 'Leipzig', 'infantry'],
      ['51st Guards Tank Regiment', 'Zeitz', 'armour'],
      ['128th Guards Artillery Regiment', 'Zeitz', 'artillery'],
      ['901st Anti-Aircraft Missile Regiment', 'Naumburg', 'air'],
      ['29th Independent Tank Battalion', 'Rudolstadt', 'armour'],
      ['651st Independent Missile Battalion', 'Naumburg', 'artillery'],
      ['491st Independent Anti-Tank Artillery Battalion', 'Naumburg', 'artillery'],
      ['113th Independent Guards Reconnaissance Battalion', 'Rudolstadt', 'infantry'],
      ['67th Independent Guards Engineer-Sapper Battalion', 'Naumburg', 'infantry'],
      ['89th Independent Guards Communications Battalion', 'Naumburg', 'infantry'],
      ['000 Independent Chemical Defence Battalion', 'Naumburg', 'infantry'], // Unusual numbering
      ['51st Independent Equipment Maintenance and Recovery Battalion', 'Naumburg', 'infantry'],
      ['75th Independent Medical Battalion', 'Naumburg', 'infantry'],
      ['1129th Independent Material Supply Battalion', 'Naumburg', 'infantry'],
      ['311th Independent Helicopter Detachment', 'Wurzen', 'air'],
      ['68th Guards Motorised Rifle Regiment', 'Halle', 'infantry'],
      ['243rd Guards Motorised Rifle Regiment', 'Halle', 'infantry'],
      ['244th Guards Motorised Rifle Regiment', 'Halle', 'infantry'],
      ['28th Tank Regiment', 'Halle', 'armour'],
      ['54th Guards Artillery Regiment', 'Halle', 'artillery'],
      ['286th Guards Anti-Aircraft Missile Regiment', 'Halle', 'air'],
      ['31st Independent Tank Battalion', 'Halle', 'armour'],
      ['329th Independent Missile Battalion', 'Halle', 'artillery'],
      ['488th Independent Anti-Tank Artillery Battalion', 'Halle', 'artillery'],
      ['5th Independent Reconnaissance Battalion', 'Halle', 'infantry'],
      ['29th Independent Guards Engineer-Sapper Battalion', 'Halle', 'infantry'],
      ['35th Independent Guards Communications Battalion', 'Halle', 'infantry'],
      ['367th Independent Chemical Defence Battalion', 'Halle', 'infantry'],
      ['44th Independent Equipment Maintenance and Recovery Battalion', 'Halle', 'infantry'],
      ['21st Independent Medical Battalion', 'Halle', 'infantry'],
      ['1126th Independent Material Supply Battalion', 'Halle', 'infantry'],
      ['327th Independent Helicopter Detachment', 'Merseburg', 'air'],
      ['16th Guards Motorised Rifle Regiment', 'Bad Freienwalde', 'infantry'],
      ['81st Guards Motorised Rifle Regiment', 'Eberswalde-Finow', 'infantry'],
      ['82nd Guards Motorised Rifle Regiment', 'Bernau', 'infantry'],
      ['68th Guards Tank Regiment', 'Bernau', 'armour'],
      ['400th Artillery Regiment', 'Frankfurt/Oder', 'artillery'],
      ['288th Guards Anti-Aircraft Missile Regiment', 'Bernau', 'air'],
      ['10th Independent Tank Battalion', 'Berlin-Karlshorst', 'armour'],
      ['351st Independent Missile Battalion', 'Fürstenwalde', 'artillery'],
      ['465th Independent Anti-Tank Missile Battalion', 'Frankfurt/Oder', 'artillery'],
      ['30th Independent Guards Reconnaissance Battalion', 'Bernau', 'infantry'],
      ['122nd Independent Guards Engineer-Sapper Battalion', 'Fürstenwalde', 'infantry'],
      ['33rd Independent Guards Communications Battalion', 'Bernau', 'infantry'],
      ['120th Independent Chemical Defence Battalion', 'Bernau', 'infantry'],
      ['32nd Independent Equipment Maintenance and Recovery Battalion', 'Bernau', 'infantry'],
      ['26th Independent Medical Battalion', 'Bernau', 'infantry'],
      ['1122nd Independent Material Supply Battalion', 'Bernau', 'infantry'],
      ['69th Motorised Rifle Regiment', 'Wünsdorf', 'infantry'],
      ['287th Guards Tank Regiment', 'Jüterbog', 'armour'],
      ['288th Guards Tank Regiment', 'Jüterbog', 'armour'],
      ['343rd Guards Tank Regiment', 'Jüterbog', 'armour'],
      ['469th Guards Artillery Regiment', 'Jüterbog', 'artillery'],
      ['1009th Anti-Aircraft Missile Regiment', 'Jüterbog', 'air'],
      ['17th Independent Tank Battalion', 'Jüterbog', 'armour'],
      ['640th Independent Missile Battalion', 'Jüterbog', 'artillery'],
      ['466th Independent Anti-Tank Artillery Battalion', 'Jüterbog', 'artillery'],
      ['32nd Independent Reconnaissance Battalion', 'Jüterbog', 'infantry'],
      ['148th Independent Guards Engineer-Sapper Battalion', 'Jüterbog', 'infantry'],
      ['211th Independent Guards Communications Battalion', 'Jüterbog', 'infantry'],
      ['22nd Independent Chemical Defence Company', 'Jüterbog', 'infantry'],
      ['19th Independent Equipment Maintenance and Recovery Battalion', 'Jüterbog', 'infantry'],
      ['636th Independent Medical Battalion', 'Jüterbog', 'infantry'],
      ['90th Independent Material Supply Battalion', 'Jüterbog', 'infantry'],
      ['62nd Motorised Rifle Regiment', 'Dallgow-Döberitz', 'infantry'],
      ['64th Motorised Rifle Regiment', 'Dallgow-Döberitz', 'infantry'],
      ['83rd Guards Motorised Rifle Regiment', 'Dallgow-Döberitz', 'infantry'],
      ['219th Tank Regiment', 'Dallgow-Döberitz', 'armour'],
      ['283rd Guards Artillery Regiment', 'Dallgow-Döberitz', 'artillery'],
      ['200th Anti-Aircraft Missile Regiment', 'Dallgow-Döberitz', 'air'],
      ['19th Independent Tank Battalion', 'Dallgow-Döberitz', 'armour'],
      ['315th Independent Missile Battalion', 'Dallgow-Döberitz', 'artillery'],
      ['485th Independent Anti-Tank Artillery Battalion', 'Dallgow-Döberitz', 'artillery'],
      ['59th Independent Reconnaissance Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['18th Independent Engineer-Sapper Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['647th Independent Communications Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['283rd Independent Chemical Defence Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['37th Independent Equipment Maintenance and Recovery Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['60th Independent Medical Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['1127th Independent Material Supply Battalion', 'Dallgow-Döberitz', 'infantry'],
      ['162nd Tank Regiment', 'Vogelsang', 'armour'], // Duplicate
      ['175th Tank Regiment', 'Prenzlau', 'armour'], // Duplicate
      ['335th Guards Tank Regiment', 'Prenzlau', 'armour'], // Duplicate
      ['803rd Guards Motorised Rifle Regiment', 'Drögen', 'infantry'], // Duplicate
      ['843rd Guards Artillery Regiment', 'Schönwalde', 'artillery'], // Duplicate
      ['447th Anti-Aircraft Missile Regiment', 'Vogelsang', 'air'], // Duplicate
      ['665th Independent Missile Battalion', 'Vogelsang', 'artillery'], // Duplicate
      ['53rd Independent Reconnaissance Battalion', 'Prenzlau', 'infantry'], // Duplicate
      ['196th Independent Engineer-Sapper Battalion', 'Vogelsang', 'infantry'], // Duplicate
      ['459th Independent Communications Battalion', 'Vogelsang', 'infantry'], // Duplicate
      ['159th Independent Chemical Defence Battalion', 'Vogelsang', 'infantry'], // Duplicate
      ['14th Independent Equipment Maintenance and Recovery Battalion', 'Vogelsang', 'infantry'], // Duplicate
      ['232nd Independent Medical Battalion', 'Vogelsang', 'infantry'], // New entry for this duplicate block
      ['1076th Independent Material Supply Battalion', 'Britz', 'infantry'], // Duplicate
      ['71st Fighter Aviation Corps', 'Wittstock', 'air'],
      ['16th Guards Fighter Aviation Division', 'Damgarten', 'air'],
      ['125th Fighter-Bomber Aviation Division', 'Rechlin', 'air'],
      ['6th Guards Fighter Aviation Division', 'Merseburg', 'air'],
      ['105th Fighter-Bomber Aviation Division', 'Grossenhain', 'air'],
      ['126th Fighter Aviation Division', 'Zerbst', 'air'],
      ['11th Independent Reconnaissance Aviation Regiment', 'Neu-Welzow', 'air'],
      ['294th Independent Reconnaissance Aviation Regiment', 'Allstedt', 'air'],
      ['931st Independent Guards Reconnaissance Aviation Regiment', 'Stendal', 'air'],
      ['226th Independent Mixed Aviation Regiment', 'Sperenberg', 'air'],
      ['39th Independent Reconnaissance Aviation Unit', 'Sperenberg', 'air'],
      ['292nd Independent Helicopter Squadron for Electronic Warfare', 'Allstedt', 'air'],
      ['74th Independent Target-Towing Aviation Squadron', 'Parchim', 'air'],
      ['65th Independent Target-Towing Aviation Squadron', 'Damgarten', 'air'],
      ['83rd Independent Communications Regiment and Automated Control Regiment', 'Rangsdorf', 'infantry'],
      ['286th Guards Howitzer Artillery Brigade', 'Potsdam', 'artillery'],
      ['288th Heavy Howitzer Artillery Brigade', 'Chemnitz', 'artillery'],
      ['303rd Guards Cannon Artillery Brigade', 'Potsdam', 'artillery'],
      ['307th Reactive Artillery Brigade', 'Chemnitz', 'artillery']
    ];

    ministrat.main.unique_locations.wto = [];

    var unique_locations = ministrat.main.unique_locations.wto;

    //Iterate over all wto_army_orbat rows
    for (var i = 0; i < wto_army_orbat.length; i++)
      if (!unique_locations.includes(wto_army_orbat[i][1]))
        if (!ministrat.config.locations[wto_army_orbat[i][1]])
          if (!ministrat.config.all_locations.includes(wto_army_orbat[i][1]))
            unique_locations.push(wto_army_orbat[i][1]);

    //Add to unique_locations
    ministrat.config.all_locations = ministrat.config.all_locations.concat(unique_locations);

    //Load all units
    setTimeout(function () {
      for (var i = 0; i < wto_army_orbat.length; i++) {
        var local_key = wto_army_orbat[i][0];
        var local_location = wto_army_orbat[i][1];
        var local_type = wto_army_orbat[i][2];

        var ministrat_location = ministrat.config.locations[local_location];

        if (local_location != "" && local_location != "(location not specified)")
          ministrat.gamestate.units[local_key] = new Ministrat_Unit({
            country: "wto",
            name: local_key,
            type: local_type,
            x: ministrat_location[0],
            y: ministrat_location[1]
          });
      }
    }, ministrat.config.rotate_animation_time);
  }
}
